services:
  postgres:
    image: postgres:16.4
    container_name: postgres_go
    volumes:
      - ./docker/volumes/postgres/data:${PGDATA}:z
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}